server:
  port: 8081

spring:
  application:
    name: flowable-monolith-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_flowable?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: linsz99@
  # 启动时自动执行建表 SQL
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

flowable:
  database-schema-update: true
  async-executor-activate: true
  history-level: audit

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
